version: "3.8"

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: vacaly

  dashboard_frontend:
    build: ./dashboard
    ports:
      - '5437:80'
    volumes:
      - data-volume:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - data-volume:/data

volumes:
  data-volume: