version: "3.8"

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: vacaly

  frontend:
    container_name: frontend
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
