version: "3.8"

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: vacaly

  frontend:
    container_name: frontend
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email yalikhan752@gmail.com --agree-tos --no-eff-email -d vacaly.kz
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot-nginx-www:/var/www/certbot
    depends_on:
      - frontend

volumes:
  certbot-nginx-www:
